### ISSUE TITLE
Image drag and drop

### ISSUE THREAD

**Issue by metrue** [mazzzystar/tinymind#8]
Trying enable deletion on thoughts in this [PR](https://github.com/mazzzystar/tinymind/pull/7), blog deletion would be nice too.

**Comment by mazzzystar** [comment]
Thanks for your work. will check the code today : )

**Comment by metrue** [comment]
I am working on this one, hope to finish it very soon.

**Comment by mazzzystar** [comment]
Hi, I've finished the `delete/edit` functionality for both posts and blogs. I hope you haven't worked on that yet.

Now I'm really interested in these two features:

1. Add a public URL so everyone can share their homepage, like `tinymind.me/metrue`, where `metrue` is the user's Github `user.login`.

2. Add a "drop/tap to upload image/audio" feature, where we create an "assets" section so users can tap to upload their images or audio (video may be too large), rather than currently using the `![](xxx)` format.

**Comment by metrue** [comment]
Both two features are very useful, I can start working on the photo drag and drop feature.

**Comment by mazzzystar** [comment]
Tips: use Cursor + Claude 3.5 Sonnet for faster coding : )
